<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <!--<Nullable>enable</Nullable>-->
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RandomString4Net" Version="1.9.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartSetList.Shared\SmartSetList.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\Artist\" />
    <Folder Include="Controllers\Search\" />
  </ItemGroup>

</Project>
